# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Run Flutter analyze and test, set version and build APK"


  lane :release do
    flutter_root = "../.."

    
    sh "cd ../.. && flutter pub get"
    sh "cd ../.. && flutter analyze"

    # Use the output of the tests to generate a coverage report
    sh "cd ../.. && flutter test --machine --coverage > tests.output" 

    # Get git commit count for versionCode
    version_code = sh("git rev-list --count HEAD").strip
    UI.message("📌 Git Commit Count as versionCode: #{version_code}")

    # Optional: version name (exemplo com data)
    version_name = Time.now.strftime("%Y.%m.%d-%H%M")
    UI.message("📌 Generated versionName: #{version_name}")

    # Build APK with versionCode and versionName
    gradle(
      task: "assembleRelease",
      properties: {
        versionCode: version_code,
        versionName: version_name
      }
    )

    UI.success("✅ APK generated successfully with versionCode #{version_code} and versionName #{version_name}")
  
  end
end